# Generated by Django 4.1.1 on 2022-09-22 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=225, null=True, unique=True, verbose_name='Email'),
        ),
    ]
